include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = autolayout
LIBRARY_NAME = libautolayout

libautolayout_HEADER_FILES = \
	GSAutoLayoutEngine.h
libautolayout_OBJCC_FILES = GSAutoLayoutEngine.mm

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/library.make
-include GNUmakefile.postamble